### ISSUE TITLE
Parsing json back into ast

### ISSUE THREAD

**Issue by sheerun** [ReconfigureIO/goblin#40]
Hey,

I'm interesting in writing a tool in language other than go-lang that generates a proper go-lang code. The easiest way I can think of, is to send go-lang source in JSON format (similar to output of goblin) to go-lang and allow it and generate proper go source.

Could you consider implementing a reverse operation in Goblin? That is parsing JSON back into AST of go-lang? If not, are you maybe aware of other libraries implementing such functionality?

**Comment by patrickt** [comment]
I think this is out of scope for goblin itself, but if you happen to write/encounter any libraries that do this, I'd be happy to link to them in the `README` (and ensure strict semver compatibility so that their upstream doesn't break.)

If you were interested in doing this yourself, it would really not be too difficult: the goblin code is long, owing to Go's somewhat low-level nature, but it's not complicated.

**Comment by sheerun** [comment]
I didn't. Thank you for response
